name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    env:                       # 実 API キーは使わない
      OPENAI_API_KEY: "dummy"
      GOOGLE_API_KEY: "dummy"
      CUSTOM_SEARCH_ENGINE_ID: "dummy"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .           # core を editable install

      - name: Ruff (lint)
        run: ruff check .

      - name: Mypy (type check)
        run: mypy --strict core

      - name: Run tests + coverage
        run: |
          pytest -q --cov=core --cov-report=xml
